name: Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
 
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload Repository
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete --exclude .venv
          path: ./
          remote_path: /var/www/hivey/backend
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.SSH_KEY }}
        
      - name: Update systemd service
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/hivey/backend && cat > .env << EOF
              ${{ secrets.ENV_FILE_CONTENT }}
            EOF
            sudo /var/www/hivey/backend/misc/scripts/update-systemd-service.sh
          
